### ISSUE TITLE
Segfault at json_t* list_perms = (json_t*) a->permissions;

### ISSUE THREAD

**Issue by azman0101** [Koodous/androguard-yara#1]
Hello,

I've an error while trying to use yara with androguard.

This is the link to one of the apk I've tested.
https://www.hex-rays.com/products/ida/support/tutorials/dalvik/MyFirstApp.apk
```bash
Starting program: /home/xxx/Downloads/yara-3.4.0/yara /home/xxx/CUCKOO_DROID/cuckoo/data/yara/index_android.yar /home/xxx/Downloads/MyFirstApp.apk
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x00000000004297ba in permission_lookup (__args=0x7fffffffcea0, __context=0x7fffffffd320, __function_obj=0x724150) at modules/androguard.c:139
139	  json_t* list_perms = (json_t*) a->permissions;
(gdb) backtrace 
#0  0x00000000004297ba in permission_lookup (__args=0x7fffffffcea0, __context=0x7fffffffd320, __function_obj=0x724150) at modules/androguard.c:139
#1  0x0000000000437a41 in yr_execute_code (rules=0x731a60, context=0x7fffffffd320, timeout=1000000, start_time=1454502170) at exec.c:558
#2  0x0000000000413bfa in yr_rules_scan_mem_blocks (rules=0x731a60, block=0x0, flags=0, callback=0x403ca8 <callback>, user_data=0x7fffffffdb48, timeout=1000000) at rules.c:427
#3  0x0000000000413e7d in yr_rules_scan_mem (rules=0x731a60, buffer=0x7ffff7f7b000 "PK\003\004\024", buffer_size=279955, flags=0, callback=0x403ca8 <callback>, user_data=0x7fffffffdb48, timeout=1000000)
    at rules.c:523
#4  0x0000000000413edf in yr_rules_scan_file (rules=0x731a60, filename=0x7fffffffdb48 "/home/xxx/Downloads/MyFirstApp.apk", flags=0, callback=0x403ca8 <callback>, user_data=0x7fffffffdb48, 
    timeout=1000000) at rules.c:548
#5  0x00000000004049a5 in main (argc=2, argv=0x7fffffffd698) at yara.c:1070
(gdb) 
```

```c
define_function(permission_lookup)
134 {
135   YR_OBJECT* obj = get_object(module(), "permission");
136   struct permissions *a;
137 
138   a = obj->data;
139   json_t* list_perms = (json_t*) a->permissions;
140   json_t* list_new_perms = (json_t*) a->new_permissions;
```
While debugging, obj seams to be correctly instanced but his data attribue is null (0x0)

**Comment by plutec** [comment]
I will try to reproduce, but have in mind that to use this module you need the report of Koodous. In this case the sample https://www.hex-rays.com/products/ida/support/tutorials/dalvik/MyFirstApp.apk hash is (sha256) 4397fae041a762e45c2081820e9528c6a3a1a71896f7f40c19a802532f8f0ec4 Therefore you need the report of this sample:
https://analyst.koodous.com/apks/4397fae041a762e45c2081820e9528c6a3a1a71896f7f40c19a802532f8f0ec4/analysis
To extract this report you can use this instructions: https://github.com/Koodous/androguard-yara#using-androguard-module
A to execute yara over the sample is:
yara -x androguard=d8adb784d08a951ebacf2491442cf90d21c20192085e44d1cd22e2b6bdd4ef5f-report.json rule.yar sample.apk

**Comment by plutec** [comment]
@azman0101 I'm trying to reproduce but not way. Is the rules public file? Could you share with us?

**Comment by azman0101** [comment]
@plutec Actually, I thought it was possible to use androguard without koodous.

There is no error when I use koodous report.

Do you want the rules despite this ?

**Comment by plutec** [comment]
@azman0101 good, I think that was an error that fixed in a intermedium commit so It's not necessary the rules file. Thanks!
