### ISSUE TITLE
yara -x rule clarity required

### ISSUE THREAD

**Issue by ghost** [Koodous/androguard-yara#14]
yara -x androguard=d8adb784d08a951ebacf2491442cf90d21c20192085e44d1cd22e2b6bdd4ef5f-report.json rule.yar sample.apk
In this rule we test the rules written in the yar file with the json report generated and sample.apk contains random content? So, basically the json and yar file are the ones of importance?
Please correct me if I'm wrong.
Any help is much appreciated.

**Comment by segura2010** [comment]
Hi @dexter0810 !

androiguard-yara is a module for yara that analyzes the report analysis extracted by Koodous. You pass the JSON report using the parameter "androguard" as you indicated in the example.

sample.apk is the APK file of the analyzed app.

You need both files to use this module.

**Comment by dexter0810** [comment]
Hi @segura2010 :) 
But, if you see this link: 
https://github.com/Koodous/androguard-yara/blob/master/.travis.yml
They've used: 
echo "trashtrashtrash" > sample.apk
implying sample.apk wasn't the apk file of the analysed app. If you would put any other content, we would get the same result.

**Comment by plutec** [comment]
It depends of the rule itself, if the rule contains other checks
furthermore the "androguard" checks, it will not works. If the rule ONLY
contains androguard checks, the match will works.

Regards!
--
Antonio Sánchez.

Web: http://www.plutec.net
E-mail: asanchez@plutec.net
Twitter: @plutec_net <http://www.twitter.com/plutec_net>

**Comment by dexter0810** [comment]
@plutec  Thanking for helping me out, I appreciate it :) 

Can you explain with an example please? I did not get you :(

**Comment by plutec** [comment]
Sure, if your rule is something like this:
```
rule test {
conditions:
  androguard.package_name("testest") or
  androguard.app_name("jkhad")
}
```
It this case, the match will works even though the APK file is empty.

In case the rule is:
```
rule test2 {
strings:
 $a = "malware"
conditions:
  androguard.package_name("testest") or
  androguard.app_name("jkhad") or
  $a
}
```
The rule needs the file (apk) to check if the string $a exists or not in it.

I hope this is helpful for you.

Regards.
--
Antonio Sánchez.

Web: http://www.plutec.net
E-mail: asanchez@plutec.net
Twitter: @plutec_net <http://www.twitter.com/plutec_net>

**Comment by dexter0810** [comment]
Now I get it, thanks a ton! :)

**Comment by plutec** [comment]
You're welcome!
