### ISSUE TITLE
undefined symbol json_integer_value

### ISSUE THREAD

**Issue by krviolet** [Koodous/androguard-yara#17]
I recompiled YARA with androguard.c as said in readme, installed yara-python, but despite that can't run the script.
python3.6 androguard_analysis.py
Traceback (most recent call last):
  File "androguard_analysis.py", line 5, in <module>
import yara
ImportError: /usr/local/lib/python3.6/dist-packages/yara_python-3.10.0-py3.6-linux-x86_64.egg/yara.cpython-36m-x86_64-linux-gnu.so: undefined symbol: json_integer_value

**Comment by roopeshiitd** [comment]
Hi, Can you please tell me resolve this issue. Me too facing the same? How did you resolve this?

**Comment by krviolent** [comment]
> Hi, Can you please tell me resolve this issue. Me too facing the same? How did you resolve this?

Hi. Unfortunately I don't remember now how I resolved this issue

**Comment by krviolent** [comment]
May be it's smth related with yara module. Yara should be installed properly
