### ISSUE TITLE
Multiple certificates

### ISSUE THREAD

**Issue by reox** [Koodous/androguard-yara#9]
It looks like that multiple certificates are not found. Here is an example of an application that has two certificates: https://koodous.com/apks/065e8c6432c66cbc83b10671f97eaeb6a8140670488a647f8dc2f540eee432a8

It contains
97f00c974bed626b11df314be3371a346aaf08de and fe5cf5ede813d4338518485faa3332973205fcb5, while in this case only the first certificate is shown in the json output.

**Comment by plutec** [comment]
This issue is not related with the module. You must contact koodous people by email (info@koodous.com)
